### ISSUE TITLE
Add external dependency on its own bundle file and load it async

### ISSUE THREAD

**Issue by ricardobrandao** [philipwalton/webpack-esnext-boilerplate#2]
Hi @philipwalton,

This setup is great, thanks for sharing it.

I would like to use this in my build, but I'm having trouble with external dependencies.

I've included momentjs, and I'm importing it inside `import-1.js` which will be part of an async chunk:
```javascript
import {dep1} from './dep-1';
import moment from 'moment';
export const import1 = `imported: ${dep1} at ${moment.now()}`;
```  
Furthermore, I'm adding momentjs as a new entry and extracting it as a vendor dependency to its own file, using the CommonChunksPlugin configuration in `bundles.js`:

```javascript
new webpack.optimize.CommonsChunkPlugin({
  name: 'moment',
}),
// Extract runtime code so updates don't affect app-code caching:
// https://webpack.js.org/guides/caching/
new webpack.optimize.CommonsChunkPlugin({
  name: opts.runtimeName || 'runtime',
}),
```

When I run the website momentjs is not being loaded and webpack throws the following error:
![screen shot 2017-11-14 at 13 19 59](https://user-images.githubusercontent.com/2292745/32781915-91719760-c93e-11e7-850c-b370bf792236.png)

I've created a [Pull Request](https://github.com/ricardobrandao/webpack-esnext-boilerplate/pull/1) with this example so please feel free to check it out.

**Comment by philipwalton** [comment]
Do you think this is an issue with Webpack or an issue with my boilerplate?

**Comment by ricardobrandao** [comment]
I believe it has to do how Webpack works. I've opened an [issue](https://github.com/webpack/webpack/issues/5956) with them.

Haven't you encountered this behaviour yet? If so, how did you handle it?

**Comment by philipwalton** [comment]
I believe the problem is you're adding `moment` to your webpack `entry` option, which I don't think is needed. When I remove that from your example, it works fine for me.
