### ISSUE TITLE
.mjs files are not minified

### ISSUE THREAD

**Issue by karpiuMG** [philipwalton/webpack-esnext-boilerplate#5]
Hello @philipwalton,

Your concept is great, thanks for sharing.

Unfortunately I faced a problem described below.

Even though I set env variable to "production", I'm not able to generate minified .mjs bundles. When I change output extension in webpack config to ".js", files are minified as they should.

Sizes of main bundles:
- main-[chunk].mjs - 54 KB
- main-[chunk].js - 18 KB

**Comment by jakub-g** [comment]
This is due to terser default config: https://github.com/webpack-contrib/terser-webpack-plugin/issues/33

I override this config in my PR: https://github.com/philipwalton/webpack-esnext-boilerplate/pull/6
